# Generated by Django 5.2 on 2026-04-23 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaResetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_upn', models.CharField(blank=True, max_length=255)),
                ('target_upn', models.CharField(blank=True, max_length=255)),
                ('target_display_name', models.CharField(blank=True, max_length=255)),
                ('target_ou', models.CharField(blank=True, max_length=255)),
                ('allowed_ous', models.TextField(blank=True)),
                ('status_code', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('list_methods_payload', models.JSONField(blank=True, null=True)),
                ('prepared_methods_payload', models.JSONField(blank=True, null=True)),
                ('reset_result_payload', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_reset_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA reset audit log',
                'verbose_name_plural': 'MFA reset audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
